### ISSUE TITLE
Not being unmounted properly

### ISSUE THREAD

**Issue by Crisfole** [6eDesign/svelte-calendar#32] opened 2019-08-06 14:41 UTC
I bumped into a bizarre bug with svelte-calendar and pagejs (?) and to keep momentum I had to move onto a different calendar component. Although I'd enthusiastically re-test this for you a I think you're currently the top svelte calendar component out there.

I can't seem to produce a minimal repro and really can't spend any more time on it, but here's an executive summary:

Under some condition (not sure which condition), the svelte-calendar component was preventing its parent components from being removed from the DOM. I'm assuming there's an `unmount` that's not being returned to clean something up, or that the unmount is asynchronous and doesn't actually resolve.

In any case, I can't safely blame svelte-calendar apart from noting that removing the calendar and replacing with a native input worked fine.

The calendar was being used like this:

```
<Calendar bind:selected={from}>
  <button class="calendar-button">
    {formatButton(from)}
  </button>
</Calendar>
```

**Comment by 6eDesign** [comment] 2019-08-06 14:46
Interesting, I'll see if I can reproduce with the pagejs router I have for svelte.  Thanks for letting me know!

**Comment by Crisfole** [comment] 2019-08-06 15:29
No problem. I definitely don't expect it to be fixed. It's working for you, which is great. I can absolutely test for you, though. Let me know

**Comment by Crisfole** [comment] 2019-08-06 15:36
Also worth noting. It wasn't the slot usage that broke it. (Got the same bug with `<Calendar bind:selected={from} />`)

**Comment by 6eDesign** [comment] 2019-08-07 22:27
@Crisfole Do you get a stack trace when this happens?  I'm seeing something similar to what you've described when I `npm link svelte-calendar` into a project but can't seem to reproduce with it installed normally.

**Comment by Crisfole** [comment] 2019-08-07 23:50
No...it just sort of sticks around... Can you push a repro? I'll test?

**Comment by antony** [comment] 2020-02-14 17:28
I think this is a duplicate of https://github.com/6eDesign/svelte-calendar/issues/65 which is better described, and it's actually a bug in Svelte.

**Comment by antony** [comment] 2020-02-14 17:33
Also relates to this issue https://github.com/sveltejs/sapper/issues/814

**Closed** 2020-02-14 20:55 UTC
Labels: cannot reproduce
